name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install Cython
      run: |
        python -m pip install --upgrade pip
        pip install cython setuptools

    - name: Convert .py to .pyx and compile
      run: |
        python setup.py build_ext --inplace

    - name: Build Docker image
      run: |
        docker build -t jfkane/somus .

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Push Docker image
      run: |
        docker tag jfkane/somus jfkane/somus:latest
        docker push jfkane/somus:latest